name: Build ROM

on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_METHOD:
        description: "Choose firmware download method"
        required: true
        type: choice
        options:
          - "samloader"
          - "direct"
          - "gdrive"
        default: "samloader"
      TELEGRAM_DESTINATION:
        description: "Release type"
        required: true
        type: choice
        options:
          - "private"
          - "public"
          - "silent"
        default: "private"
      FIRMWARE_DIRECT_LINK:
        description: "Direct firmware link or Google Drive FILE_ID (only direct link, google drive)"
        required: false
      TARGET_DEVICE_MODEL:
        description: "Target device model"
        required: true
        default: "SM-"
      BASE_DEVICE_MODEL:
        description: "Base device model (ROM Base)"
        required: true
        default: "SM-"
      SAMLOADER_CSC_IMEI:
        description: "CSC/IMEI e.g. EUX/000000000 (only samloader)"
        required: false
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is 5.4 (lower than 5.10)."
        required: true
        type: choice
        options:
          - "True"
          - "False"
        default: "False"
      OUTPUT_FILESYSTEM:
        description: "OUTPUT_FILESYSTEM."
        required: true
        type: choice
        options:
          - "erofs"
          - "ext4"
        default: "erofs"

jobs:
  build:
    name: Start scripts.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Fetch CoreEngine Source
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/rhn-1k/Coreproject.git core_temp
          cp -r core_temp/* .
          rm -rf core_temp
          chmod +x *.py scripts/*.py 2>/dev/null || true

      - name: Cleaning junk files
        uses: rokibhasansagar/slimhub_actions@v25.42.5

      - name: Setup environment
        run: |
          python3 setup.py

      - name: Check inputs
        run: |
          SAMLOADER_CSC_IMEI="${{ github.event.inputs.SAMLOADER_CSC_IMEI }}"

          if [[ "${{ github.event.inputs.DOWNLOAD_METHOD }}" == "samloader" ]]; then
            if [[ ! "$SAMLOADER_CSC_IMEI" =~ ^[^/]+/[^/]+$ ]]; then
              echo "ERROR: SAMLOADER_CSC_IMEI must be in format CSC/IMEI"
              exit 1
            fi
          fi

          BASE_MODEL="${{ github.event.inputs.BASE_DEVICE_MODEL }}"
          BASE_CSC=$(echo "$SAMLOADER_CSC_IMEI" | cut -d'/' -f1)
          BASE_IMEI=$(echo "$SAMLOADER_CSC_IMEI" | cut -d'/' -f2)

          echo "BASE_MODEL=$BASE_MODEL" >> $GITHUB_ENV
          echo "BASE_CSC=$BASE_CSC"     >> $GITHUB_ENV
          echo "BASE_IMEI=$BASE_IMEI"   >> $GITHUB_ENV

      - name: Download firmware
        run: |
          METHOD="${{ github.event.inputs.DOWNLOAD_METHOD }}"

          LINK_OR_IMEI="${{ github.event.inputs.DOWNLOAD_METHOD == 'samloader' && env.BASE_IMEI || github.event.inputs.FIRMWARE_DIRECT_LINK }}"

          python3 scripts/download.py \
            "${{ env.BASE_MODEL }}" \
            "$METHOD" \
            "$LINK_OR_IMEI" \
            "${{ env.BASE_CSC }}"

      - name: Start Build From ${{ github.event.inputs.BASE_DEVICE_MODEL }} To ${{ github.event.inputs.TARGET_DEVICE_MODEL }}
        run: |
          python3 sixteen.py \
            "${{ github.event.inputs.TARGET_DEVICE_MODEL }}" \
            "${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" \
            "${{ env.BASE_MODEL }}" \
            "${{ env.BASE_CSC }}" \
            "${{ env.BASE_IMEI }}" \
            "${{ github.event.inputs.OUTPUT_FILESYSTEM }}"

      - name: Compress and Upload to Google Drive
        run: |
          OUT_DIR="OUT"
          VERSION=$(cat version.txt | tr -d '[:space:]')
          DATE=$(date +'%Y-%m-%d')
          ZIP_NAME="CoreUI_V${VERSION}_${DATE}.7z"

          ZIP_PATH="$OUT_DIR/$ZIP_NAME"
          7z a -t7z "$ZIP_PATH" ./"$OUT_DIR"/* -mx=9
          python3 upload.py "$ZIP_PATH" "${{ github.event.inputs.TELEGRAM_DESTINATION }}"
