name: Sync Version to Source

on:
  workflow_dispatch:
  push:
    paths:
      - 'version.txt'

jobs:
  update-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and Push to Source
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/rhn-1k/Coreproject.git core_priv
          cd core_priv
          bash scripts/gen_version.sh

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add core/etc/web/data/version.json version.txt

          if ! git diff --quiet --staged; then
            git commit -m "Web: Sync version to $(cat version.txt | cut -d',' -f1)"
            git push origin HEAD
          else
            echo "No changes detected."
          fi
