name: Sync Version to Private Repo

on:
  workflow_dispatch:
  push:
    paths:
      - 'version.txt'

jobs:
  update-private-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and Push to Private Repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/rhn-1k/Coreproject.git private_repo
          cp version.txt private_repo/
          cd private_repo

          chmod +x gen_version.sh
          bash gen_version.sh

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add core/etc/web/data/version.json version.txt

          if ! git diff --quiet --staged; then
            git commit -m "Web: Sync version to $(cat version.txt | cut -d',' -f1)"
            git push origin HEAD
          else
            echo "No changes detected."
          fi
